name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    name: Tests (Python ${{ matrix.python-version }} • ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11", "3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Prepare Git for test repos
        shell: bash
        run: |
          git config --global user.email "ci@example.com"
          git config --global user.name "CI"
          git config --global --add safe.directory "*"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install project (dev)
        run: python -m pip install -e ".[dev]"

      - name: Show environment
        shell: bash
        run: |
          python --version
          pip --version
          python -c "import sys, platform; print(platform.platform()); import lockstep_rebase as m; print('lockstep_rebase', getattr(m, '__version__', 'unknown'))"

      - name: Run tests
        run: pytest -q

      - name: CLI smoke test (editable install)
        shell: bash
        run: |
          lockstep-rebase --help > /dev/null 2>&1 || python -c "import shutil,sys; sys.exit(0 if shutil.which('lockstep-rebase') else 1)"

  install-check:
    name: Install Check (Python ${{ matrix.python-version }} • ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11", "3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install package
        run: python -m pip install .

      - name: Verify import
        run: python -c "import lockstep_rebase as m; print(getattr(m,'__version__','unknown'))"

      - name: CLI smoke test (wheel/sdist install)
        shell: bash
        run: lockstep-rebase --help | head -n 5
